version: 1.1

jobs:
  build:
  use-action:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch API Data 📦
      uses: JamesIves/fetch-api-data-action@releases/v1
      with:
          ENDPOINT: https://cdn.contentful.com/spaces/5zdu8tl44dyz/environments/prod/content_types?access_token=8K4vUmyqa6GAImzJ5Vyz7QZI6KUYtIQxbrYz5ICTrGg
          SAVE_LOCATION: contentful/data.json
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: main
        message: 'contentful: autopublish ${date}'

workflows:
  version: 1
  gitconnect:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - circleci-project-setup
