version: 2.1

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Fetch API Data 📦
      uses: JamesIves/fetch-api-data-action@releases/v1
      with:
          ENDPOINT: https://cdn.contentful.com/spaces/bxxzjfpinfqw/environments/dev/content_types?access_token=i9NVv2CZw-ybTGentOo1rEqGR-OO2Y1bXbptT6383kw
          SAVE_LOCATION: contentful/data.json
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: main
        message: 'contentful: autopublish ${date}'
          
workflows:
  version: 2.1
  gitconnect:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - circleci-project-setup
