version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.5
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: Clone docs
          working_directory: ~/workdir
          command: |
            git clone -b circleci-project-setup --depth 1 https://github.com/ravikumar-pandey/contentful-cicd.git
      - run: ls


workflows:
  version: 2
  build_develop:    
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - circleci-project-setup
