version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.5
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: wget -O content_type https://cdn.contentful.com/spaces/bxxzjfpinfqw/environments/dev/content_types?access_token=i9NVv2CZw-ybTGentOo1rEqGR-OO2Y1bXbptT6383kw

workflows:
  version: 2
  build_develop:    
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - circleci-project-setup
