version: 2.1

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Fetch API Data 📦
      uses: JamesIves/fetch-api-data-action@v2.1.0
      with:
          ENDPOINT: https://cdn.contentful.com/spaces/bxxzjfpinfqw/environments/dev/content_types?access_token=i9NVv2CZw-ybTGentOo1rEqGR-OO2Y1bXbptT6383kw
          SAVE_LOCATION: contentful/data.json
  commit:
    steps:
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: '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'
        branch: circleci-project-setup
        message: 'contentful: autopublish ${date}'
          
workflows:
  version: 2.1
  gitconnect:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - circleci-project-setup
       - commit:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci-project-setup

