version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.5
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: wget -O content_type https://cdn.contentful.com/spaces/bxxzjfpinfqw/environments/dev/content_types?access_token=i9NVv2CZw-ybTGentOo1rEqGR-OO2Y1bXbptT6383kw
      - run: readlink -f content_type.txt
      - run: ls
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/workdir/contentful
          command: |
            git add .
            git config user.email "ravikumar.pandey@infosys.com"
            git config user.name "ravikumar-pandey"
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push

workflows:
  version: 2
  build_develop:    
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - circleci-project-setup
