version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.5
      
    working_directory: ~/repo
    
    steps:
      - checkout
      
      - run:
          name: Clone docs
          working_directory: ~/repo
          command: |
            git clone -b circleci-project-setup --depth 1 https://github.com/ravikumar-pandey/contentful-cicd.git

      - deploy:
          name: Trigger docs deployment
          working_directory: ~/repo/contentful-cicd
          command: |
            wget -O content_type https://cdn.contentful.com/spaces/bxxzjfpinfqw/environments/dev/content_types?access_token=i9NVv2CZw-ybTGentOo1rEqGR-OO2Y1bXbptT6383kw
            ls
            git add .
            git config user.email "ravikumar.pandey@infosys.com"
            git config user.name "ravikumar-pandey"
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push


workflows:
  version: 2
  build_develop:    
    jobs:
      - build:
          filters:
            tags:
              only: /contentful-.*/
            branches:
              only:
                - circleci-project-setup
